# Generated by Django 2.0.2 on 2018-02-25 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0002_auto_20180225_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stipend',
            name='invitation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rsvp.Invitation'),
        ),
    ]
