# Generated by Django 2.0.2 on 2018-02-25 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rsvp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', related_query_name='ballot', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('self_nomination', models.BooleanField(default=False)),
                ('success', models.BooleanField(default=False)),
                ('camp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rsvp.Camp')),
                ('nominated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations', related_query_name='nomination', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user', models.ManyToManyField(related_name='tags', related_query_name='tag', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nod.Ballot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', related_query_name='vote', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VotingRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(default='New voting round', max_length=25)),
                ('description', models.TextField(blank=True, null=True)),
                ('num_votes', models.PositiveSmallIntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsvp.Camp')),
            ],
        ),
        migrations.AddField(
            model_name='ballot',
            name='voting_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nod.VotingRound'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'ballot')},
        ),
        migrations.AlterUniqueTogether(
            name='nomination',
            unique_together={('nominated_by', 'camp', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='ballot',
            unique_together={('voter', 'voting_round')},
        ),
    ]
